- name: ensure keystone packages are installed
  apt: name={{ item }} 
  with_items:
    - keystone

  
- name: ensure sqlite keystone database is deleted
  file: dest=/var/lib/keystone/keystone.db state=absent

- name: ensure keystone config script is present
  template: >
    src=etc/keystone/keystone.conf
    dest=/etc/keystone/keystone.conf
    owner=keystone
    group=keystone
    mode=0600

- name: DB sync for keystone
  shell: >
    /usr/bin/keystone-manage db_sync
  notify: restart keystone

- name: ensure apache2 servername is config
  template: >
    src=etc/apache2/apache2.conf
    dest=/etc/apache2/apache2.conf
    owner=root
    group=root
    mode=0600
  notify: restart keystone
